name: release-tag
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        id: create-tag
        run: |
          git fetch origin main
          git checkout main
          echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///' > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
          echo "::set-output name=tag-name::$(cat TAG_NAME)"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-tag.outputs.tag-name }}
          release_name: Release ${{ steps.create-tag.outputs.tag-name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
